# Generated by Django 3.2.3 on 2021-06-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_accountnumber', models.CharField(max_length=16)),
                ('to_accountnumber', models.CharField(max_length=16)),
                ('amount', models.FloatField()),
                ('note', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
